apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}-secret
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.Password | quote }}
