---
- name: Create dir block
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /var/rsm-data/opt/docker/jenkins
    - ./jenkins
  tags:
    - update_jenkins

- name: Copy compose files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - {src: 'docker-compose.yml',dest: './jenkins/docker-compose.yml', mode: "0755"}
    - {src: 'Dockerfile.jenkins',dest: './jenkins/Dockerfile.jenkins', mode: "0755"}
    - {src: 'jenkins_private',dest: '/var/rsm-data/opt/docker/jenkins/', mode: "0700"}
  tags:
    - update_jenkins

- name: Run docker-compose build
  command: docker-compose build
  args:
    chdir: ./jenkins
  tags:
    - update_jenkins

- name: Run docker-compose UP
  command: docker-compose up -d
  args:
    chdir: ./jenkins
  tags:
    - update_jenkins
