trigger: none
pr: none

pool:
  vmImage: "ubuntu-20.04"

parameters:
- name: Environment
  type: string
  default: TEST
  values:
    - TEST

variables:
- group: anfisa-backend-${{ parameters.Environment }}

jobs:

  - job: BackendDockerBuild
    displayName: "Backend docker build"

    steps:
      - checkout: self
        clean: true

      - task: Bash@3
        displayName: 'Update build number'
        inputs:
          workingDirectory: 'app'
          targetType: inline
          script: |
            anfisaVersion="$(grep -Eo '[0-9]\.[0-9]\.[0-9]+' ./VERSION)"
            echo "##vso[build.updatebuildnumber]${anfisaVersion}.$(Build.BuildId)"
            echo $(Build.SourceBranchName)

      - task: Docker@2
        displayName: 'Docker build and push'
        inputs:
          containerRegistry: $(azContainerRegistry)
          repository: $(azRepository)
          Dockerfile: Dockerfile
          buildContext: .
          tags: $(Build.BuildNumber)
          addPipelineData: false
          addBaseImageData: false

      - task: PublishPipelineArtifact@1
        displayName: 'Publish helm as artifact'
        inputs:
          path: helm
          artifactName: helm
