resources:
  repositories:
    - repository: Helm
      type: git
      name: Forome/helm

trigger: none
pr: none

pool:
  vmImage: "ubuntu-latest"

variables:
- group: anfisa-backend-BUILD

jobs:

  - job: BackendDockerBuild
    displayName: "Backend docker build"

    steps:
      - checkout: self
        clean: true

      - task: Bash@3
        displayName: 'Update build number'
        inputs:
          workingDirectory: 'anfisa/app'
          targetType: inline
          script: |
            anfisaVersion="$(awk '{print $2}' VERSION)"
            anfisaBuild="$(awk '{print $1}' BUILD-HASH)"
            echo "##vso[build.updatebuildnumber]${anfisaVersion}.${anfisaBuild}.$(Build.BuildId)"

      - task: Docker@2
        displayName: 'Docker build and push'
        inputs:
          containerRegistry: $(azContainerRegistry)
          repository: $(azRepository)
          Dockerfile: anfisa/setup/Dockerfile
          buildContext: anfisa
          tags: $(Build.BuildNumber)
          addPipelineData: false
          addBaseImageData: false

      - checkout: Helm

      - task: PublishPipelineArtifact@1
        displayName: 'Publish helm as artifact'
        inputs:
          path: helm/anfisa
          artifactName: helm
