apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: anfisa-frontend
  labels:
    app: {{ .Values.anfisa_front.name }}
spec:
  host: >-
    {{ .Values.ingress.host }}
  path: /
  to:
    kind: Service
    name: anfisa-frontend
    weight: 100
  port:
    targetPort: anfisa-frontend
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  wildcardPolicy: None

