facets:
- facet: knowledge_domain
  title: Knowledge Domain
  variants:
  - id: call
    name: Call Annotations
  - id: phenotype
    name: Phenotypic Data
  - id: rules
    name: Compound Rules
  - id: popgen
    name: Population Genetics
  - id: function
    name: Functional Genetics
  - id: animal
    name: Animal Genetics
  - id: human
    name: Human Genetics
  - id: epigenetics
    name: Epigenetics
  - id: na
    name: N/A
- facet: scale
  title: Scale
  variants:
  - id: transcript
    name: Variant in Transcript
  - id: variant
    name: Variant
  - id: position
    name: Position
  - id: window
    name: Window
  - id: gene
    name: Gene
  - id: na
    name: N/A
- facet: method
  title: Method
  variants:
  - id: statgen
    name: Statistical Genetics Evidence
  - id: bioinf
    name: Bioinformatics Inference
  - id: in-vivo
    name: Experimental, in Vivo
  - id: in-vitro
    name: Experimental, in Vitro
  - id: exp
    name: Experimental, Other
  - id: clinical
    name: Clinical Evidence
  - id: raw
    name: Raw Data
  - id: na
    name: N/A
- facet: purpose
  title: Purpose
  variants:
  - id: evidence
    name: Evidence
  - id: phenotype
    name: Phenotype
  - id: provenance
    name: Provenance
lists:
- list: Most_Severe_Consequence
  values:
  - transcript_ablation
  - splice_acceptor_variant
  - splice_donor_variant
  - stop_gained
  - frameshift_variant
  - stop_lost
  - start_lost
  - transcript_amplification
  - inframe_insertion
  - inframe_deletion
  - missense_variant
  - protein_altering_variant
  - incomplete_terminal_codon_variant
  - start_retained_variant
  - stop_retained_variant
  - synonymous_variant
  - splice_region_variant
  - coding_sequence_variant
  - mature_miRNA_variant
  - 5_prime_UTR_variant
  - 3_prime_UTR_variant
  - non_coding_transcript_exon_variant
  - intron_variant
  - NMD_transcript_variant
  - non_coding_transcript_variant
  - upstream_gene_variant
  - downstream_gene_variant
  - TFBS_ablation
  - TFBS_amplification
  - TF_binding_site_variant
  - regulatory_region_ablation
  - regulatory_region_amplification
  - feature_elongation
  - regulatory_region_variant
  - feature_truncation
  - intergenic_variant
  - splice_polypyrimidine_tract_variant
  - splice_donor_region_variant
  - splice_donor_5th_base_variant
  - undefined
- list: Chromosome
  values:
  - chr1
  - chr2
  - chr3
  - chr4
  - chr5
  - chr6
  - chr7
  - chr8
  - chr9
  - chr10
  - chr11
  - chr12
  - chr13
  - chr14
  - chr15
  - chr16
  - chr17
  - chr18
  - chr19
  - chr20
  - chr21
  - chr22
  - chr23
  - chrX
  - chrY
  - undefined
maps:
- map: In_hg19
  values:
    None: Unmapped
- map: HGMD_Benign
  values:
    'True': Benign
    'False': VUS or Pathogenic
