FROM jenkins/jenkins:lts
USER root
RUN apt update -y && apt install python3-pip -y && pip3 install ansible && wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.9.tgz && tar xzvf docker-19.03.9.tgz && cp docker/* /usr/bin/