apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: 
type: Opaque
data:
  {{- if not (eq (include "postgresql.username" .) "postgres")  }}
  postgresql-postgres-password: ZHJ1aWRyb290Cg==
  {{- end }}
  postgresql-password: ZHJ1aWQK
  {{- if .Values.replication.enabled }}
  postgresql-replication-password: {{ include "postgresql.replication.password" . | b64enc | quote }}
  {{- end }}
  {{- if (and .Values.ldap.enabled .Values.ldap.bind_password)}}
  postgresql-ldap-password: {{ .Values.ldap.bind_password | b64enc | quote }}
  {{- end }}
