apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.annotator.name }}
  name: {{ .Values.annotator.name }}
spec:
  ports:
  - name: {{ .Values.annotator.name }}
    port: 80
    protocol: TCP
    targetPort: 3142
  selector:
    app: {{ .Values.annotator.name }}
  sessionAffinity: None
  type: ClusterIP
