#kind: Ingress
apiVersion: networking.k8s.io/v1beta1
#apiVersion: config.openshift.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.anfisa.project }}
spec:
  tls:
    - hosts:
        - >-
          {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.certificate }}
  rules:
    - host: >-
        {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: anfisa-frontend
              servicePort: 80
          - path: /anfisa/app
            pathType: ImplementationSpecific
            backend:
              serviceName: anfisa-backend
              servicePort: 80
