apiVersion: "v1"
kind: PersistentVolumeClaim
metadata:
  name: s3pvc
  annotations:
    ibm.io/auto-create-bucket: "true"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "{{ .Values.volumeclaim.bucket }}"
    ibm.io/secret-name: "{{ .Values.volumeclaim.secret }}"
spec:
  storageClassName: ibmc-s3fs-standard-regional
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "1000Gi"