name: anfisa-back
# git_uri: https://github.com/ForomePlatform/anfisa.git
# git_branch: helm
# output_registry: image-registry.openshift-image-registry.svc:5000

ingress:
  name: anfisa-ingress
  host: __ingressHost__
  certificate: __ingressCert__

image:
  repository: forome.azurecr.io/anfisa
  pullPolicy: IfNotPresent
  tag: "0.7.5.helm"

imagePullSecrets:
  - name: anfisa-registry

imageCredentials:
  registry: forome.azurecr.io
  username: __imageUsername__
  password: __imagePassword__

bucketCredentials:
  accessKey: __bucketAccessKey__
  secretKey: __bucketSecretKey__

env:
  - name: ANFISA_COORD_HOST
    value: anfisa-druid-coordinator
  - name: ANFISA_ROUTER_HOST
    value: router
  - name: ANFISA_MONGO_HOST
    value: anfisa-mongodb
  - name: BACKEND
    value: 127.0.0.1:3041
  - name: ANFISA_WORK
    value: "/anfisa/a-setup"
  - name: ANFISA_SRC
    value: "/anfisa"
  - name: ANFISA_HTML_APP_BASE
    value: "/app"
  - name: ANFISA_HTML_TITLE
    value: "Anfisa"
  - name: ANFISA_DRUIDVAULTPREFIX
    value: "demo_v7"
  - name: ANFISA_DRUIDINDEX
    value: "http://anfisa-druid-coordinator:8081/druid/indexer/v1/task"
  - name: ANFISA_DRUIDCOORD
    value: "http://anfisa-druid-coordinator:8081/druid/coordinator/v1"
  - name: ANFISA_DRUIDSQL
    value: "http://router:80/druid/v2/sql"
  - name: ANFISA_DRUIDQUERY
    value: "http://router:80/druid/v2"
  - name: ANFISA_DRUIDCOPYDIR
    value: "/data/anfisa"
  - name: ANFISA_MONGOHOST
    value: "anfisa-mongodb"
  - name: ANFISA_MONGODB
    value: "Anfisa1"
  - name: ANFISA_MONGOPORT
    value: 27017