#!/bin/bash
for d in /anfisa/a-setup/{data,logs,vault,export/work,ui} ; do
    [ ! -d $d ] && mkdir -p $d
done
if [ ! -f /anfisa/a-setup/export/SEQaBOO_output_template_20190317.xlsx ]  ; then
  pushd /anfisa/a-setup/export
  curl -L -O https://www.dropbox.com/s/4dvunn3dusqc636/SEQaBOO_output_template_20190317.xlsx
  popd
fi

exec "$@"
