apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: {{ .Values.anfisa.name }}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.anfisa.git_uri }}
      ref: {{ .Values.anfisa.git_branch }}
  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
      dockerfilePath: setup/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.anfisa.name }}:latest"
