kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.anfisa.name }}-uwsgi-ini
  namespace: {{ .Values.anfisa.project }}
data:
  uwsgi.ini: |
    [uwsgi]
    socket = 127.0.0.1:3041
    # http-socket = 127.0.0.1:3041
    chdir = /anfisa/
    wsgi-file = /anfisa/anfisa/app/run.py
    pythonpath = /anfisa/anfisa/
    processes = 1
    threads = 30
    logger = file:logfile=/anfisa/a-setup/logs/uwsgi.log,maxsize=500000
    lazy