apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: anfisa
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 0
        runAsUser: 0
        runAsGroup: 0
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers: 
        - name: {{ .Values.name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.env }}
          env:
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          ports:
          # image: "{{ .Values.output_registry }}/{{ .Release.Namespace }}/{{ .Values.name }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          stdin: true
          # command: [ "/bin/bash" ]
          # args: [ "-c", "sleep infinity" ]
          # command: [ "/entrypoint.sh" ]
          # args: [ "/usr/local/bin/supervisord" ]
          volumeMounts:
          - name: forome-anfisa
            mountPath: /data/anfisa/
          - name: anfisa-workdir
            mountPath: /anfisa/a-setup/
          - name: forome-datasets-pvc
            mountPath: /mnt/forome-datasets
          # - name: back-anfisa-config
          #   mountPath: /anfisa/anfisa.json
          #   subPath: anfisa.json
          # - name: back-nginx-config
          #   # mountPath: /etc/nginx/sites-enabled/default
          #   mountPath: /etc/nginx/conf.d/default.conf
          #   subPath: anfisa.conf
          # - name: back-uwsgi-config
          #   mountPath: /anfisa/uwsgi.ini
          #   subPath: uwsgi.ini
      volumes:
      - name: forome-anfisa
        persistentVolumeClaim:
          claimName: forome-anfisa-s3-pvc
      - name: anfisa-workdir
        persistentVolumeClaim:
          claimName: anfisa-workdir-claim
      - name: forome-datasets-pvc
        persistentVolumeClaim:
          claimName: forome-datasets-pvc
      # - name: back-anfisa-config
      #   configMap:
      #     name: back-anfisa-config
      #     defaultMode: 0666
      # - name: back-nginx-config
      #   configMap:
      #     name: back-nginx-config
      #     defaultMode: 0666
      # - name: back-uwsgi-config
      #   configMap:
      #     name: back-uwsgi-config
      #     defaultMode: 0666
      terminationGracePeriodSeconds: 5