apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    meta.helm.sh/release-namespace: {{ .Values.anfisa.project }}
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.anfisa.project }}
spec:
  tls:
    - hosts:
        - >-
          {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.certificate }}
  rules:
    - host: >-
        {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: anfisa-frontend
                port:
                  number: 80
          - path: /app
            pathType: ImplementationSpecific
            backend:
              service:
                name: anfisa-backend
                port:
                  number: 80
