apiVersion: v1
kind: Service
metadata:
  name: anfisa-backend
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: None
  selector:
    app: {{ .Values.name }}