name: ui-autotests-run

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    
jobs:
  api_tests:
    runs-on: ubuntu-latest      
    defaults:
        run:
        working-directory: api_tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.10.0
        
      - name: Local modules install
        run: pipenv install
        working-directory: .
        
      - name: Run tests
        run: pipenv run tests
        working-directory: .