name: ui-autotests-run

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
    
jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
        
      - name: Install pipenv
        run: pip install pipenv
        
      - name: Local modules install
        if: ${{ always() }}
        run: pipenv install
        working-directory: ./api_tests
        
      - name: Run tests
        if: ${{ always() }}
        run: pipenv run tests_report
        working-directory: ./api_tests