# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: front-nginx-config
# data:
#   default.conf: |
#     server {
#         listen 80;
#         server_name _;

#         location /app {
#             include uwsgi_params;
#             uwsgi_read_timeout 3000;
#             uwsgi_buffering off;
#             uwsgi_pass http://anfisa-backend;
#         }

#         location ~ /app/ui/images {
#             proxy_pass http://anfisa-backend;
#         }

#         location ~ /app/ui {
#             proxy_pass http://anfisa-backend;
#         }

#         location / {
#             client_max_body_size 100M;
#             proxy_buffering off;
#             proxy_read_timeout 3000;
#             root /usr/share/nginx/html/anfisa/;
#             try_files $uri $uri/ /index.html;
#         }
#     }
# ---
kind: ConfigMap
apiVersion: v1
metadata:
  name: front-env-config
data:
  env-config.js: |
    window._env_ = {
      REACT_APP_URL_BACKEND: '{{ .Values.anfisa_front.url_backend }}'
    }