kind: ConfigMap
apiVersion: v1
metadata:
  name: front-nginx-config
data:
  Anfisa.conf: |
    upstream backend {
        server anfisa-backend;
    }
    server {
        listen 80;
        location /app {
            include uwsgi_params;
            uwsgi_read_timeout 3000;
            uwsgi_buffering off;
            uwsgi_pass anfisa-backend:80;
        }
        location ~ /app/ui/images {
            proxy_pass http://anfisa-backend:80;
        }
        location ~ /app/ui {
            proxy_pass http://anfisa-backend:80;
        }
        location / {
            client_max_body_size 100M;
            proxy_buffering off;
            proxy_read_timeout 3000;
            root /usr/share/nginx/html/Anfisa/;
            try_files $uri $uri/ /index.html;
      }
      location /bams {
            root /datatest;
          # autoindex on;
      }
    }

