kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.anfisa_front.name }}
  labels:
    app: {{ .Values.anfisa_front.name }}
spec:
  selector:                
    matchLabels:     
      app: {{ .Values.anfisa_front.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.anfisa_front.name }}
    spec:
      serviceAccountName: default
      serviceAccount: default
      securityContext:
        fsGroup: 1000
        runAsUser: 0
      containers:
      - name: {{ .Values.anfisa_front.name }}
        image: {{ .Values.anfisa.output_registry }}/{{ .Values.anfisa.project }}/{{ .Values.anfisa_front.name }}:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: front-env-config
            mountPath: /usr/share/nginx/html/Anfisa/env-config.js
            subPath: env-config.js
          - name: front-nginx-config
            mountPath: /etc/nginx/conf.d/Anfisa.conf
            subPath: Anfisa.conf
      volumes:
        - name: front-env-config
          configMap:
            name: front-env-config
            defaultMode: 0666
        - name: front-nginx-config
          configMap:
            name: front-nginx-config
            defaultMode: 0666
      restartPolicy: Always
